config/routes.rb
Rails.application.routes.draw do

    get '/searches/university' => 'searches#university'
    post '/searches/university' => 'searches#show_results'

    resources :courses
    resources :courses_users
    resources :searches
    resources :universities
    resources :profiles 
    post '/universities/:id' => 'universities#show'

    resources :discussions
  mount Forem::Engine, :at => '/forums'

  devise_for :users
  resources :dashboard
  resources :about

  root to: 'home#index'

  post '/subjects' => 'subjects#create'

end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :universities
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :university  
  has_many :courses_users
  has_many :users, :through => :courses_users
end 

app/models/courses_user.rb
class CoursesUser < ActiveRecord::Base
	belongs_to :user
	belongs_to :course
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
	validates :title, presence: true, length: {minimum: 5}
	validates :body,  presence: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
 has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/models/subject.rb
class Subject < ActiveRecord::Base
 belongs_to :user
end

app/models/university.rb
class University < ActiveRecord::Base
	has_many :courses 
	belongs_to :country
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attached_file :avatar, styles: { medium: "300x300#", thumb: "100x100#" }, :default_url => "/images/thumb/missing.jpg"
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def forem_name
    username
  end
  has_many :subjects
  has_many :courses_users
  has_many :courses, :through => :courses_users
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
before_action :verify_is_admin, except: [:index, :show]



	def index
		@discussions = Discussion.all
	end
	def show 
		@discussion = Discussion.find(params[:id])
	end
	def new
		@discussion = Discussion.new
	end
	def create
		@discussion = Discussion.new(discussion_params)

		if @discussion.save
			redirect_to @discussion
		else
			render 'new'
		end
	end
		def edit
		@discussion = Discussion.find(params[:id])
	end

	def update
		@discussion = Discussion.find(params[:id])

		if @discussion.update(params[:discussion].permit(:title, :body, :image))
			redirect_to @discussion
		else
			render 'edit'
		end
	end

	def destroy
		@discussion = Discussion.find(params[:id])
		@discussion.destroy

		redirect_to discussions_path
	end
	
	private

	def discussion_params
		params.require(:discussion).permit(:title, :body, :image)
	end

	def verify_is_admin
  		 authenticate_user!

  		if current_user.admin
     			return
  		else
  		 	redirect_to :controller=>'dashboard', :action => 'index'
		end
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/university_helper.rb
module UniversityHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/discussions/edit.html.erb
	

<br><br><br>
<h1 align="center">Edit Post</h1>
<div class="border-form-div">
<%= form_for @discussion do |f| %>
	<% if @discussion.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@discussion.errors.count, "error") %> prevented this discussion from saving:</h2>
			<ul>
				<% @discussion.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= f.label :title %><br>
	<%= f.text_field :title %><br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_field :body %><br>
	<br>
	<%= f.label :image %><br>
	<%= f.text_field :image %><br>
	<br>
	<%= f.submit %>
<% end %>
</div>

app/views/discussions/index.html.erb
<div class="col-md-2">
	<%= render('layouts/sidebar.html.erb') %>
</div>
<div class="container">
<h2 class="lead title_dashboard">Featured Discussions</h2>
  <div class="row col-md-8">
	<% @discussions.each do |discussion| %>
		<div class="col-sm-6">
			<h2 class="lead"><%= link_to discussion.title, discussion_path(discussion) %></h2>
			<img src='<%= asset_path(discussion.image) %>'  class="img-responsive">
		</div>
	<% end %>

</div>
</div>


	<%= render('layouts/footer.html.erb') %>

app/views/discussions/new.html.erb
<br><br><br>
<div class="border-form-div">
<%= form_for @discussion do |f| %>
	<% if @discussion.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@discussion.errors.count, "error") %> prevented this discussion from saving:</h2>
			<ul>
				<% @discussion.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= f.label :title %><br>
	<%= f.text_field :title %><br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_field :body %><br>
	<br>
	<%= f.label :image %><br>
	<%= f.text_field :image %><br>
	<br>
	<%= f.submit %>
<% end %>
</div>

app/views/discussions/show.html.erb
<div class="col-md-2">
	<%= render('layouts/sidebar.html.erb') %>
</div>
<div class="container">
	<img src='<%= asset_path( @discussion.image) %>' id="image_blog" class="img-responsive">
	
	<article>
        <div class="container">
            <div class="row">
                <div class="col-lg-7  col-md-10 col-md-offset-2">
                <h2 class="lead title_dashboard"><%= @discussion.title %></h2>
                	<p>
						<% if user_signed_in? && current_user.admin?%>
							| <%= link_to 'Edit', edit_discussion_path(@discussion) %> |
						  <%= link_to 'Delete', discussion_path(@discussion), method: :delete, data: { confirm: 'Are you sure?' } %>
	 					 <% end %>
					</p>
					<%= @discussion.body %>
				</div>
            </div>
        </div>
	</article>
</div>

	<%= render('layouts/footer.html.erb') %>