config/routes.rb
Rails.application.routes.draw do

    get '/searches/university' => 'searches#university'
    post '/searches/university' => 'searches#show_results'

    resources :courses
    resources :courses_users
    resources :searches
    resources :universities
    resources :profiles 
    post '/universities/:id' => 'universities#show'

    resources :discussions
  mount Forem::Engine, :at => '/forums'

  devise_for :users
  resources :dashboard
  resources :about

  root to: 'home#index'

  post '/subjects' => 'subjects#create'

end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :universities
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :university  
  has_many :courses_users
  has_many :users, :through => :courses_users
end 

app/models/courses_user.rb
class CoursesUser < ActiveRecord::Base
	belongs_to :user
	belongs_to :course
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
	validates :title, presence: true, length: {minimum: 5}
	validates :body,  presence: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
 has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/models/subject.rb
class Subject < ActiveRecord::Base
 belongs_to :user
end

app/models/university.rb
class University < ActiveRecord::Base
	has_many :courses 
	belongs_to :country
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attached_file :avatar, styles: { medium: "300x300#", thumb: "100x100#" }, :default_url => "/images/thumb/missing.jpg"
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def forem_name
    username
  end
  has_many :subjects
  has_many :courses_users
  has_many :courses, :through => :courses_users
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if user_signed_in?
			redirect_to :controller=>'dashboard', :action => 'index'
		end
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/university_helper.rb
module UniversityHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="jumbotron1">
	<div class="jumbo-container">
        <h1 id="title_jumbo">A Global Hub for <br> High-School Students</h1>
        <h2 id="subtitle_jumbo">Become a member of our international community</h2>
        <%= link_to "Join Us for Free »", new_user_registration_path, :class => "btn btn-success", :id => "button_jumbo" %>
    </div>
</div>
<div class="bs-docs-featurette"> 
  <div class="container">
    <h2 class="bs-docs-featurette-title">Helping international students to succeed</h2>
    <p class="lead"> We are the academic community for students with a global mindset. Get informed about your best college options. Resolve with your peers questions about your academic subjects.</p>

    <hr class="half-rule">

    <div class="row">
      <div class="col-sm-4">
        <img src="<%= asset_path( 'library.jpg' ) %>" class="img-responsive">
        <h3>Forum</h3>
        <p>An international high-school program is always a challenge and sometimes it is better to get some help from your colleagues even if they are in the other side of the globe. Our <%= link_to 'forums', forem.forums_path %> deals with your subjects and with everything related to colleges and univesities.</p>
      </div>
      <div class="col-sm-4">
        <img src="<%= asset_path( 'london.jpg' ) %>" class="img-responsive">
        <h3>University Search</h3>
        <p>Our <a href="../searches/university">university search</a> is customized for international students and looks into different countries at the same time by course and expected high-school grades. Save your searches to compare and decide where to apply.</p>
      </div>
      <div class="col-sm-4">
        <img src="<%= asset_path( 'Post.jpg' ) %>" class="img-responsive">
        <h3>Featured Discussions</h3>
        <p>We put together experts, fellow students and international university students to present accurate and unfiltered information about the best course and university recommendations. Join our <%= link_to "featured discussions", discussions_path %></a>.</p>
      </div>
    </div>
  </div>
</div>
<%= render('layouts/footer.html.erb') %>